name: AWS CloudFormation deploy

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: aws-actions/setup-sam@v1

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: SAM validate
        run: sam validate -t bot_deployment.yaml

      - name: SAM build
        run: sam build -t bot_deployment.yaml

  deploy:
    runs-on: ubuntu-latest
    needs: 
      - validate
    # if: 
    #   github.ref == 'refs/heads/main'

    steps:
      - uses: actions/checkout@v2

      - uses: aws-actions/setup-sam@v1

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: SAM build
        run: sam build -t bot_deployment.yaml
        
      - name: SAM deploy
        run: sam deploy --no-confirm-changeset --no-fail-on-empty-changeset --resolve-s3 --region ${{secrets.AWS_REGION}} --parameter-overrides "GymBaseUrl=${{ secrets.GYM_BASE_URL }} GymLocation=${{ secrets.GYM_LOCATION }} GymEmail=${{ secrets.GYM_EMAIL }} GymPassword=${{ secrets.GYM_PASSWORD }}"
