name: AWS CloudFormation deploy

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: aws-actions/setup-sam@v1

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: SAM build
        run: sam build -t cd/bot_deployment.yaml

      - name: SAM deploy
        run: sam deploy --no-confirm-changeset --no-fail-on-empty-changeset --resolve-s3 --region ${{secrets.AWS_REGION}} -t cd/bot_deployment.yaml --parameter-overrides "GymBaseUrl=${{ secrets.GYM_BASE_URL }}"
        
